id: PDCC1314C
initial_creation_type: input
source_metadata:
  title: Buddha Śākyamuni Prayers & Practices
  language: es
  description: 'Lotsawa House presents the following texts as part of its Prayers
    to Buddha Śākyamuni Series:'
  volume:
    3ef6b0ad74ab498cbdc6db8363571bf5:
      title: Prayer for the Future of the Dharma
      parent: Aspiration Prayers
    ae468ebbb93c4de3baeb5936abc8cee5:
      title: 'The King of Aspiration Prayers: Samantabhadra''s “Aspiration to Good
        Actions” (Zangchö Mönlam)'
      parent: Aspiration Prayers
    9e5ca074edfb4dccb33d501a760e20d7:
      title: 'The Sage''s Powerful Words of Truth: A Prayer for the Spread of the
        Omniscient Buddha''s Teachings'
      parent: Aspiration Prayers
    0e6f00d326dc4331b73877f65eee5f30:
      title: Verses on the Buddha's Previous Lives
      parent: History
    4989155c8d8749d484015f9da952711e:
      title: Short Praise of the Buddha's Deeds
      parent: Buddha's Deeds
    7d43895f193a4c5ca5ae7f1c9cbcf517:
      title: Praise of the Twelve Acts of the Buddha
      parent: Buddha's Deeds
    674dd842ab064d8abbc8fb34d761a1e6:
      title: 'Praise of the Buddha: With Skilful Means & Compassion...'
      parent: Buddha's Deeds
    e6d095775fd04aa4bbc9be7135617551:
      title: Verses of Homage to the Buddhas and Bodhisattvas Together with their
        Mantras
      parent: Praise
    89502bd987114b2fb9ba3e98ee6bd167:
      title: A Brief Practice of Paying Homage and Making Offerings to the Sixteen
        Elders
      parent: Sādhanas
    4934cd2142cf4714b53e6e4332bc27ed:
      title: 'The Heart of Wish-Fulfilling Jewels: A Brief Practice for Paying Homage
        and Making Offerings to the Buddha together with his retinue of Arhats'
      parent: Sādhanas
    eb9ffebbad6c47c7bf84f6f78129c7d3:
      title: A Practice of Paying Homage and Making Offerings to the Sixteen Elders
      parent: Sādhanas
    92f058072a9549dcadc18d2390dc180f:
      title: 'The Treasury of Blessings: A Practice of Buddha Śākyamuni'
      parent: Sādhanas
    73db8bbcb3a442eba6c42f97895cb5bc:
      title: 'The Sage who Dispels Mind’s Anguish: Advice from the Guru, the Gentle
        Protector Mañjuśrī on the Means of Accomplishing the Yogas of Śamatha and
        Vipaśyanā'
      parent: Commentaries
created_at: '2022-03-01T03:05:43.224920'
last_modified_at: '2022-03-01T03:05:43.224922'
